name: "WaterME"
version: "0.0.9"
slug: "waterme"
description: "WaterME Irrigation Controller Add-on"
url: "https://github.com/goatboynz/ha-WaterME"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - config:rw
  - share:rw
options: {}
schema: {}
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 8099
panel_icon: "mdi:water"
panel_title: "WaterME"
panel_admin: false
