name: "WaterME"
version: "0.1.9"
slug: "waterme"
description: "Professional-grade irrigation controller for precision crop steering - Inspired by Vaultify."
url: "https://github.com/goatboynz/ha-WaterME"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - config:rw
  - share:rw
options: {}
schema: {}
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 8099
panel_icon: "mdi:water-boiler"
panel_title: "WaterME"
panel_admin: false
icon: true
logo: true
